#define WIRED_DEVICE    "enp9s0"
#define WIRELESS_DEVICE "wlp3s0"
#define INTERVAL        1
#define VOL_CH          "Master"
#define BAT_NOW         "/sys/class/power_supply/BAT1/energy_now"
#define BAT_FULLL        "/sys/class/power_supply/BAT1/energy_full"
#define BAT_STATE       "/sys/class/power_supply/BAT1/status"
#define BAT_VOLTAGE     "/sys/class/power_supply/BAT1/voltage_now"
#define BAT_CURRENT     "/sys/class/power_supply/BAT1/power_now"

#define MPD         "%s: %s - %s"
#define NO_MPD      ""
#define LAN         "Connected"
#define NO_CON      "No connection"
#define VOL_MUTE    "M %d%%"
#define VOL         "V %d%%"
#define BAT_FULL    "F"
#define BAT_DIS     "D %d%%, %02d:%02d"
#define BAT_CHRG    "C %d%%, %02d:%02d"
#define BAT_UNK     "U"
#define NO_BAT      "N"
#define CLK         "%a %d %b, %R"
#define NO_CLK      "Unable"
